### ISSUE TITLE
Visa Sponsorship Information Missing on LinkedIn for Ultimate UK Visa Extension

### ISSUE THREAD

**Issue by srividya-98** [kart33k/UkVisaSponsorChecker#3]
Dear Support Team,

I hope this email finds you well. I am writing to bring to your attention an issue regarding the Ultimate UK Visa sponsorship extension feature on LinkedIn. While this feature is successfully displayed on the Indeed website, it seems to be missing or not functioning correctly on LinkedIn.

As a user who heavily relies on LinkedIn for professional networking and job search, I have encountered difficulties in identifying companies that offer visa sponsorship for the Ultimate UK Visa extension program. The absence of this crucial information on LinkedIn puts individuals like myself at a disadvantage when searching for potential job opportunities.

I kindly request your assistance in addressing this issue and ensuring that the Ultimate UK Visa sponsorship extension feature is properly displayed on LinkedIn. This would greatly benefit international professionals who rely on LinkedIn for career development and visa sponsorship opportunities.

Please let me know if there is any additional information or details that I can provide to assist you in resolving this matter.Sharing the LinkedIn job screenshot for reference. I appreciate your prompt attention to this issue and your dedication to improving the user experience on GitHub and its affiliated platforms.

Thank you for your understanding and support.

Sincerely,
Srividya

![image](https://github.com/kart33k/UkVisaSponsorChecker/assets/67091103/497c922b-408b-4ebe-81eb-702c1913168a)

**Comment by kart33k** [comment]
Thank you for your email.
We will look into this and get back to you as soon as possible.
Please give us some time.

**Comment by kart33k** [comment]
Hi Srividya,
A new version with fix for LInkedIn was released on 28/06.
Please verify. Also please share this extension with your friends and will be grateful if you leave a nice review.
Thanks you
